# Generated by Django 4.1.3 on 2022-11-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contect',
            new_name='con',
        ),
    ]
